server:
  port: ${SERVER_PORT:8010}
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
      min-spare: 100


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'api-auth'
      paths-to-match: '/**'
      packages-to-scan: com.brenden.cloud
  info:
    title: 认证模块
    description: 用户认证与授权
    contact-name: brenden.luo
    contact-email: brenden.luo@gmail.com
    version: v1.0.0
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  documents:
    - group: 认证模块
      name: auth

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.brenden.cloud.**.persistence.domain
  global-config:
    db-config:
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false