server:
  port: ${SERVER_PORT:8010}
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 100
logging:
  config: classpath:logback-spring.xml
  path: ../logs/
#  后续需要迁移至配置中心
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      connect-timeout: 30000
      timeout: 30000
      client-type: lettuce